sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

branches:
  only:
  - master
  - develop
  - release-*

after_success:
  - mvn clean cobertura:cobertura coveralls:report -P coveralls.io

